### ISSUE TITLE
Allow node v12

### ISSUE THREAD

**Issue by fraserredmond** [TypeFox/find-git-exec#15]
Hi, I'm trying to install theia which has find-git-exec as a dependency, but it stops on the error:

error find-git-exec@0.0.2: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "12.13.1"

Any chance of getting it working for the current version of node?

**Comment by 502647092** [comment]
I try build a theia docker image
but base image node version is 12.x
can allow node 12

**Comment by MagnoCorrea** [comment]
I'm oppened an Pull request to perform this upgrade. https://github.com/TypeFox/find-git-exec/pull/16
